localPath = scriptPath()
imagePath = (localPath .. "image/")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/agi.png", imagePath .."agi.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/endV1.png", imagePath .."endV1.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/exp.png", imagePath .."exp.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/exp.png", imagePath .."exp.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/fleur.png", imagePath .."fleur.png")
toast("25%")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/hp.png", imagePath .."hp.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/level.png", imagePath .."level.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/lobbyHp.png", imagePath .."lobbyHp.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/loot.png", imagePath .."loot.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/magnolia1.png", imagePath .."magnolia1.png")
toast("50%")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/merchant.png", imagePath .."merchant.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/midPoint2.png", imagePath .."midPoint2.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/missionGo.png", imagePath .."missionGo.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/placa.png", imagePath .."placa.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/point.png", imagePath .."point.png")
toast("75%")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/rest.png", imagePath .."rest.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/route.png", imagePath .."route.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/stage.png", imagePath .."stage.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/str.png", imagePath .."str.png")
httpDownload("https://raw.githubusercontent.com/bruno105/AnkuLua/master/PostKnight/image/yellowNpc.png", imagePath .."yellowNpc.png")
toast("100%")
scriptExit("Updates Completed")